version: '3.8'
services:

  postgres-account:
    image: postgres:14
    environment:
      POSTGRES_DB: account
      POSTGRES_USER: account
      POSTGRES_PASSWORD: account123
    ports:
      - "5432:5432"

  postgres-payments:
    image: postgres:14
    environment:
      POSTGRES_DB: payments
      POSTGRES_USER: payments
      POSTGRES_PASSWORD: payments123
    ports:
      - "5433:5432"

  auth-simulation:
    build:
      context: ./auth-simulation
    ports:
      - "8090:8080"

  gateway:
    build:
      context: ./gateway
    ports:
      - "8081:8080"

  ms-payments:
    build:
      context: ./mspayments
    environment:
      - DATABASE_HOST=postgres-payments
    ports:
      - "8082:8080"
    depends_on:
      - postgres-payments

  ms-account:
    build:
      context: ./msaccount
    environment:
      - DATABASE_HOST=postgres-account
    ports:
      - "8083:8080"
    depends_on:
      - postgres-account