
spring:
  application:
    name: gateway

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/auth/realms/payment-system

  cloud:
    gateway:
      routes:
        - id: payment-service
          uri: http://localhost:8082
          predicates:
            - Path=/payments/**