spring:
  application:
    name: gateway

  cloud:
    gateway:
      routes:
        - id: auth
          uri: http://auth-simulation:8080
          predicates:
            - Path=/auth/**

        - id: payment-service
          uri: http://ms-payments:8080
          predicates:
            - Path=/payments/**
          filters:
            - AuthFilter

auth:
  uri: http://auth-simulation:8080

logging:
  level:
    root: debug