spring:
  application:
    name: ms-payments

  datasource:
    username: payments
    password: payments123
    url: jdbc:postgresql://postgres-payments:5432/payments

client:
  account:
    url: http://localhost:8083